version: '3.10'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'aa123456'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    restart: unless-stopped
  db-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-gpt
    ports:
      - 7860:7860
    expose:
      - 7860
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1', '0']
              capabilities: [gpu]

volumes:
  my-db:
